# Generated by Django 4.2.4 on 2023-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('available', models.BooleanField(default=True)),
                ('last_order', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
