# Generated by Django 4.2.4 on 2023-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='close_money',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
